CREATE TABLE Producto(
	idProductoPK VARCHAR(5) NOT NULL,
	nombre VARCHAR(60) NOT NULL,
	precio MONEY NOT NULL,
	imagen VARCHAR(60) NOT NULL,
	esPizza BIT NOT NULL,
	CONSTRAINT PK_PRODUCTO PRIMARY KEY (idProductoPK) 
);

CREATE TABLE Ingrediente(
	idIngredientePK VARCHAR(5) NOT NULL,
	nombre VARCHAR(60) NOT NULL,
	precio MONEY NOT NULL,
	imagen VARCHAR(60) NOT NULL,
	CONSTRAINT PK_INGREDIENTE PRIMARY KEY (idIngredientePK) 
);

CREATE TABLE Combo(
	idComboPK VARCHAR(5),
	nombre VARCHAR(60),
	precio MONEY NOT NULL,
	imagen VARCHAR(60) NOT NULL,
	CONSTRAINT PK_COMBO PRIMARY KEY (idComboPK) 
)

CREATE TABLE ComboTiene(
	idComboFK VARCHAR(5),
	idProductoFK VARCHAR(5),
	CONSTRAINT PK_COMBOTIENE PRIMARY KEY(idComboFK, idProductoFK),
	CONSTRAINT FK_COMBOTIENE_COMBO FOREIGN KEY(idComboFK) REFERENCES Combo(idComboPK)
	ON UPDATE CASCADE
	ON DELETE NO ACTION,
	CONSTRAINT FK_COMBOTIENE_PRODUCTO FOREIGN KEY(idProductoFK) REFERENCES Producto(idProductoPK)
	ON UPDATE CASCADE
	ON DELETE NO ACTION,
)